-- liquibase formatted sql

-- changeset Хозяин:1659525298390-7
CREATE TABLE collections
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255),
    enable VARCHAR(255),
    CONSTRAINT pk_collections PRIMARY KEY (id)
);

-- changeset Хозяин:1659525298390-8
CREATE TABLE collections_movies
(
    collections_id BIGINT NOT NULL,
    movies_id      BIGINT NOT NULL,
    CONSTRAINT pk_collections_movies PRIMARY KEY (collections_id, movies_id)
);

-- changeset Хозяин:1659525298390-9
CREATE TABLE content
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content_url VARCHAR(255),
    movie_id    BIGINT,
    CONSTRAINT pk_content PRIMARY KEY (id)
);

-- changeset Хозяин:1659525298390-10
CREATE TABLE folders_movies_to_movies
(
    folders_id BIGINT NOT NULL,
    movie_id   BIGINT NOT NULL,
    CONSTRAINT pk_folders_movies_to_movies PRIMARY KEY (folders_id, movie_id)
);

-- changeset Хозяин:1659525298390-11
CREATE TABLE genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

-- changeset Хозяин:1659525298390-12
CREATE TABLE genres_movies
(
    genres_id BIGINT NOT NULL,
    movies_id BIGINT NOT NULL,
    CONSTRAINT pk_genres_movies PRIMARY KEY (genres_id, movies_id)
);

-- changeset Хозяин:1659525298390-13
CREATE TABLE movies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    countries    VARCHAR(255),
    date_release BIGINT,
    rars         INTEGER                                 NOT NULL,
    mpaa         INTEGER                                 NOT NULL,
    time         INTEGER                                 NOT NULL,
    description  VARCHAR(255),
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

-- changeset Хозяин:1659525298390-14
CREATE TABLE news_movie
(
    movie_id BIGINT NOT NULL,
    news_id  BIGINT NOT NULL,
    CONSTRAINT pk_news_movie PRIMARY KEY (movie_id, news_id)
);

-- changeset Хозяин:1659525298390-15
CREATE TABLE score
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_id  BIGINT,
    user_id   BIGINT,
    score     BIGINT,
    movies_id BIGINT,
    CONSTRAINT pk_score PRIMARY KEY (id)
);

-- changeset Хозяин:1659525298390-16
ALTER TABLE users
    ADD avatar_url VARCHAR(255);

-- changeset Хозяин:1659525298390-17
ALTER TABLE movie_person
    ADD movie_id BIGINT;
ALTER TABLE movie_person
    ADD type_person VARCHAR(255);

-- changeset Хозяин:1659525298390-18
ALTER TABLE awards_ceremony_result
    ADD movies_id BIGINT;

-- changeset Хозяин:1659525298390-20
ALTER TABLE persons_marriage
    ADD CONSTRAINT uc_28ef9ec715257f5c99f15ec0e UNIQUE (person_id, human_id);

-- changeset Хозяин:1659525298390-22
ALTER TABLE awards_ceremony_result
    ADD CONSTRAINT FK_AWARDSCEREMONYRESULT_ON_MOVIES FOREIGN KEY (movies_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-23
ALTER TABLE content
    ADD CONSTRAINT FK_CONTENT_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-24
ALTER TABLE movie_person
    ADD CONSTRAINT FK_MOVIE_PERSON_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-25
ALTER TABLE score
    ADD CONSTRAINT FK_SCORE_ON_MOVIES FOREIGN KEY (movies_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-26
ALTER TABLE collections_movies
    ADD CONSTRAINT fk_colmov_on_collections FOREIGN KEY (collections_id) REFERENCES collections (id);

-- changeset Хозяин:1659525298390-27
ALTER TABLE collections_movies
    ADD CONSTRAINT fk_colmov_on_movies FOREIGN KEY (movies_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-28
ALTER TABLE folders_movies_to_movies
    ADD CONSTRAINT fk_folmovtomov_on_folder_movies FOREIGN KEY (folders_id) REFERENCES folders_movies (id);

-- changeset Хозяин:1659525298390-29
ALTER TABLE folders_movies_to_movies
    ADD CONSTRAINT fk_folmovtomov_on_movies FOREIGN KEY (movie_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-30
ALTER TABLE genres_movies
    ADD CONSTRAINT fk_genmov_on_genres FOREIGN KEY (genres_id) REFERENCES genres (id);

-- changeset Хозяин:1659525298390-31
ALTER TABLE genres_movies
    ADD CONSTRAINT fk_genmov_on_movies FOREIGN KEY (movies_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-32
ALTER TABLE news_movie
    ADD CONSTRAINT fk_newmov_on_movies FOREIGN KEY (movie_id) REFERENCES movies (id);

-- changeset Хозяин:1659525298390-33
ALTER TABLE news_movie
    ADD CONSTRAINT fk_newmov_on_news FOREIGN KEY (news_id) REFERENCES news (id);

-- changeset Хозяин:1659525298390-34
ALTER TABLE user_avatar DROP CONSTRAINT fklatwcvwggmxieyymk3e3aah09;

-- changeset Хозяин:1659525298390-35
DROP TABLE user_avatar CASCADE;

-- changeset Хозяин:1659525298390-36
ALTER TABLE movie_person DROP COLUMN type_character;

-- changeset Хозяин:1659525298390-37
DROP SEQUENCE gen_awards CASCADE;

-- changeset Хозяин:1659525298390-38
DROP SEQUENCE gen_awards_ceremony CASCADE;

-- changeset Хозяин:1659525298390-39
DROP SEQUENCE gen_awards_ceremony_result CASCADE;

-- changeset Хозяин:1659525298390-40
DROP SEQUENCE gen_nomination CASCADE;

-- changeset Хозяин:1659525298390-1
CREATE SEQUENCE IF NOT EXISTS awards_id_seq;
ALTER TABLE awards
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE awards
    ALTER COLUMN id SET DEFAULT nextval('awards_id_seq');
ALTER SEQUENCE awards_id_seq OWNED BY awards.id;

-- changeset Хозяин:1659525298390-2
CREATE SEQUENCE IF NOT EXISTS awards_ceremony_id_seq;
ALTER TABLE awards_ceremony
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE awards_ceremony
    ALTER COLUMN id SET DEFAULT nextval('awards_ceremony_id_seq');
ALTER SEQUENCE awards_ceremony_id_seq OWNED BY awards_ceremony.id;

-- changeset Хозяин:1659525298390-3
CREATE SEQUENCE IF NOT EXISTS awards_ceremony_result_id_seq;
ALTER TABLE awards_ceremony_result
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE awards_ceremony_result
    ALTER COLUMN id SET DEFAULT nextval('awards_ceremony_result_id_seq');
ALTER SEQUENCE awards_ceremony_result_id_seq OWNED BY awards_ceremony_result.id;

-- changeset Хозяин:1659525298390-4
CREATE SEQUENCE IF NOT EXISTS nomination_id_seq;
ALTER TABLE nomination
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE nomination
    ALTER COLUMN id SET DEFAULT nextval('nomination_id_seq');
ALTER SEQUENCE nomination_id_seq OWNED BY nomination.id;

-- changeset Хозяин:1659525298390-6
ALTER TABLE movie_person
    ADD CONSTRAINT pk_movie_person PRIMARY KEY (person_id, movie_id, profession_id);

